# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Author: Diego Gomez Mosquera
trigger:
- '*'

pool:
  vmImage: 'ubuntu-20.04'

stages:
- stage: Heroku_Deploy
  displayName: Bash Script Config y Deploy
  jobs:
  - job: Heroku_Deploy
    displayName: Bash Script Config y Deploy
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
                 cat >~/.netrc <<EOF
                     machine api.heroku.com
                       login $(heroku_email)
                       password $(api_key)
                     machine git.heroku.com
                       login $(heroku_email)
                       password $(api_key)
                 EOF
                 chmod 600 ~/.netrc
                 tail ~/.netrc
                 heroku apps
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
                  git checkout $(Build.SourceBranchName)
                  git remote add heroku https://heroku:$(api_key)@git.heroku.com/spring-boot-azure-pipelines.git
                  git push heroku $(Build.SourceBranchName)